### ISSUE TITLE
Facing issue while reading api key that is required for writing unit tests

### ISSUE THREAD

**Issue by getElastic** [angular-magic/ngx-gp-autocomplete#7]
Hi there!

We are making use of this package in our Angular frontend app. While writing unit testcases for the same, facing some challenge. Facing an issue on trying to import an api key.  Inspite of passing an api key, its failing to read the api key.

Below is the error we encounter.

```
TypeError: Cannot read properties of undefined (reading 'apiKey')

      32 |     //formBuilder = TestBed.inject(FormBuilder);
      33 |     component = fixture.componentInstance;
>   34 |     fixture.detectChanges();
           |             ^
      35 |   });
      36 |
      37 |   afterEach(() => TestBed.resetTestingModule());

      at new libraries (node_modules/@googlemaps/js-api-loader/src/index.ts:292:5)
      at NgxGpAutocompleteDirective.ngAfterViewInit (node_modules/@angular-magic/ngx-gp- 
  autocomplete/fesm2020/angular-magic-ngx-gp-autocomplete.mjs:39:9)
      at callHookInternal (node_modules/@angular/core/fesm2022/core.mjs:3852:14)
      at callHook (node_modules/@angular/core/fesm2022/core.mjs:3879:13)
      at callHooks (node_modules/@angular/core/fesm2022/core.mjs:3834:17)
      at executeInitAndCheckHooks (node_modules/@angular/core/fesm2022/core.mjs:3784:9)
      at refreshView (node_modules/@angular/core/fesm2022/core.mjs:12560:21)
      at detectChangesInView (node_modules/@angular/core/fesm2022/core.mjs:12653:9)
      at detectChangesInComponent (node_modules/@angular/core/fesm2022/core.mjs:12629:5)
      at detectChangesInChildComponents (node_modules/@angular/core/fesm2022/core.mjs:12667:9)
      at refreshView (node_modules/@angular/core/fesm2022/core.mjs:12539:13)
      at detectChangesInternal (node_modules/@angular/core/fesm2022/core.mjs:12431:9)
      at RootViewRef.detectChanges (node_modules/@angular/core/fesm2022/core.mjs:12945:9)
      at ComponentFixture._tick (node_modules/@angular/core/fesm2022/testing.mjs:126:32)
      at node_modules/@angular/core/fesm2022/testing.mjs:139:22
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (node_modules/zone.js/bundles/zone.umd.js:412:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/bundles/zone-testing.umd.js:300:43)
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (node_modules/zone.js/bundles/zone.umd.js:411:56)
      at Object.onInvoke (node_modules/@angular/core/fesm2022/core.mjs:26321:33)
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (node_modules/zone.js/bundles/zone.umd.js:411:56)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/bundles/zone.umd.js:166:47)
      at NgZone.run (node_modules/@angular/core/fesm2022/core.mjs:26175:28)
      at ComponentFixture.detectChanges (node_modules/@angular/core/fesm2022/testing.mjs:138:25)
      at src/app/modules/vehicle/reserve-vehicle/reserve-vehicle.component.spec.ts:34:13
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (node_modules/zone.js/bundles/zone.umd.js:412:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/bundles/zone-testing.umd.js:300:43)
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (node_modules/zone.js/bundles/zone.umd.js:411:56)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/bundles/zone.umd.js:166:47)
      at Object.wrappedFunc (node_modules/zone.js/bundles/zone-testing.umd.js:789:34)
      
      101 |     setTimeout(() => {
      102 |
  > 103 |       fixture.detectChanges();
            |               ^
      104 |
      105 |       expect(true).toBe(true);
      106 |

      at new libraries (node_modules/@googlemaps/js-api-loader/src/index.ts:292:5)
      at NgxGpAutocompleteDirective.ngAfterViewInit (node_modules/@angular-magic/ngx-gp-autocomplete/fesm2020/angular-magic-ngx-gp-autocomplete.mjs:39:9)
      at callHookInternal (node_modules/@angular/core/fesm2022/core.mjs:3852:14)
      at callHook (node_modules/@angular/core/fesm2022/core.mjs:3879:13)
      at callHooks (node_modules/@angular/core/fesm2022/core.mjs:3834:17)
      at executeInitAndCheckHooks (node_modules/@angular/core/fesm2022/core.mjs:3784:9)
      at refreshView (node_modules/@angular/core/fesm2022/core.mjs:12560:21)
      at detectChangesInView (node_modules/@angular/core/fesm2022/core.mjs:12653:9)
      at detectChangesInComponent (node_modules/@angular/core/fesm2022/core.mjs:12629:5)
      at detectChangesInChildComponents (node_modules/@angular/core/fesm2022/core.mjs:12667:9)
      at refreshView (node_modules/@angular/core/fesm2022/core.mjs:12539:13)
      at detectChangesInternal (node_modules/@angular/core/fesm2022/core.mjs:12431:9)
      at RootViewRef.detectChanges (node_modules/@angular/core/fesm2022/core.mjs:12945:9)
      at ComponentFixture._tick (node_modules/@angular/core/fesm2022/testing.mjs:126:32)
      at node_modules/@angular/core/fesm2022/testing.mjs:139:22
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (node_modules/zone.js/bundles/zone.umd.js:412:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/bundles/zone-testing.umd.js:300:43)
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (node_modules/zone.js/bundles/zone.umd.js:411:56)
      at Object.onInvoke (node_modules/@angular/core/fesm2022/core.mjs:26321:33)
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (node_modules/zone.js/bundles/zone.umd.js:411:56)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/bundles/zone.umd.js:166:47)
      at NgZone.run (node_modules/@angular/core/fesm2022/core.mjs:26175:28)
      at ComponentFixture.detectChanges (node_modules/@angular/core/fesm2022/testing.mjs:138:25)
      at src/app/modules/vehicle/reserve-vehicle/reserve-vehicle.component.spec.ts:103:15
      at timer (node_modules/zone.js/bundles/zone.umd.js:2442:47)
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invokeTask (node_modules/zone.js/bundles/zone.umd.js:446:35)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvokeTask (node_modules/zone.js/bundles/zone-testing.umd.js:331:43)
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invokeTask (node_modules/zone.js/bundles/zone.umd.js:445:64)
      at Zone.Object.<anonymous>.Zone.runTask (node_modules/zone.js/bundles/zone.umd.js:211:51)
      at Object.<anonymous>.ZoneTask.invokeTask (node_modules/zone.js/bundles/zone.umd.js:528:38)
      at ZoneTask.invoke (node_modules/zone.js/bundles/zone.umd.js:517:52)
      at data.args.<computed> (node_modules/zone.js/bundles/zone.umd.js:2422:36)
      at Timeout.task [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:520:19)

```

**Comment by dancornilov** [comment]
Hey, can you provide a full test file, or some repository when we can reproduce this error. 

But before that ensure that you **import** module in your TestBed module.

```
await TestBed.configureTestingModule({
imports: [...

      NgxGpAutocompleteModule.forRoot({
            loaderOptions: {
              apiKey: 'YOUR_KEY',
              libraries: ['places'],
            },
          }),
]
});
  ```
